#define upperbound_x 16  //豎軸最大邊界
#define lowerbound_x 0	 //豎軸最小邊界
#define upperbound_y 68  //橫軸最大邊界
#define lowerbound_y 0   //橫軸最小邊界
#define FACE_width 68    //介面尺寸
#define FACE_length 16   //介面尺寸
#define total_iter 5   //敷蛋倒數計時
#define infancy_life_max 10 //幼年期最大生命
#define growth_life_max 12 //成長期最大生命